# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#10141A"

# Main text color
theme[main_fg]="#D8DFE8"

# Title color for boxes
theme[title]="#D8DFE8"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#9BC6FF"

# Background color of selected item in processes box
theme[selected_bg]="#475971"

# Foreground color of selected item in processes box
theme[selected_fg]="#FFFFFF"

# Color of inactive/disabled text
theme[inactive_fg]="#95A2A9"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#EDF1F6"

# Background color of the percentage meters
theme[meter_bg]="#475971"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#EDF1F6"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#F9D0FF"
theme[mem_box]="#8DFEDB"
theme[net_box]="#F5825E"
theme[proc_box]="#9BC6FF"

# Box divider line and small boxes line color
theme[div_line]="#95A2A9"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#8DFEDB"
theme[temp_mid]="#FCCA39"
theme[temp_end]="#F5825E"

# CPU graph colors (Teal -> Blue -> Magenta)
theme[cpu_start]="#53C1DA"
theme[cpu_mid]="#9BC6FF"
theme[cpu_end]="#F9D0FF"

# Mem/Disk free meter
theme[free_start]="#F9D0FF"
theme[free_mid]="#9BC6FF"
theme[free_end]="#53C1DA"

# Mem/Disk cached meter
theme[cached_start]="#9BC6FF"
theme[cached_mid]="#53C1DA"
theme[cached_end]="#F9D0FF"

# Mem/Disk available meter
theme[available_start]="#FCCA39"
theme[available_mid]="#F5825E"
theme[available_end]="#F5825E"

# Mem/Disk used meter (Green -> Teal -> Blue)
theme[used_start]="#8DFEDB"
theme[used_mid]="#53C1DA"
theme[used_end]="#9BC6FF"

# Download graph colors
theme[download_start]="#FCCA39"
theme[download_mid]="#F5825E"
theme[download_end]="#F5825E"

# Upload graph colors (Green -> Teal -> Blue)
theme[upload_start]="#8DFEDB"
theme[upload_mid]="#53C1DA"
theme[upload_end]="#9BC6FF"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#53C1DA"
theme[process_mid]="#9BC6FF"
theme[process_end]="#F9D0FF"

# Graph gradient colors (spectrum shades from background to foreground)
theme[gradient_color_0]="#10141A"
theme[gradient_color_1]="#1B2029"
theme[gradient_color_2]="#475971"
theme[gradient_color_3]="#95A2A9"
theme[gradient_color_4]="#A3AEBD"
theme[gradient_color_5]="#D8DFE8"
theme[gradient_color_6]="#EDF1F6"
theme[gradient_color_7]="#FFFFFF"
