# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#FAF9F6"

# Main text color
theme[main_fg]="#2B2B28"

# Title color for boxes
theme[title]="#2B2B28"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#003A77"

# Background color of selected item in processes box
theme[selected_bg]="#8BA0BA"

# Foreground color of selected item in processes box
theme[selected_fg]="#0F0F0E"

# Color of inactive/disabled text
theme[inactive_fg]="#4B575E"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#1C1C1A"

# Background color of the percentage meters
theme[meter_bg]="#8BA0BA"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#1C1C1A"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#781A61"
theme[mem_box]="#003D18"
theme[net_box]="#62000A"
theme[proc_box]="#003A77"

# Box divider line and small boxes line color
theme[div_line]="#4B575E"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#003D18"
theme[temp_mid]="#664500"
theme[temp_end]="#62000A"

# CPU graph colors (Teal -> Blue -> Magenta)
theme[cpu_start]="#005F6B"
theme[cpu_mid]="#003A77"
theme[cpu_end]="#781A61"

# Mem/Disk free meter
theme[free_start]="#781A61"
theme[free_mid]="#003A77"
theme[free_end]="#005F6B"

# Mem/Disk cached meter
theme[cached_start]="#003A77"
theme[cached_mid]="#005F6B"
theme[cached_end]="#781A61"

# Mem/Disk available meter
theme[available_start]="#664500"
theme[available_mid]="#62000A"
theme[available_end]="#62000A"

# Mem/Disk used meter (Green -> Teal -> Blue)
theme[used_start]="#003D18"
theme[used_mid]="#005F6B"
theme[used_end]="#003A77"

# Download graph colors
theme[download_start]="#664500"
theme[download_mid]="#62000A"
theme[download_end]="#62000A"

# Upload graph colors (Green -> Teal -> Blue)
theme[upload_start]="#003D18"
theme[upload_mid]="#005F6B"
theme[upload_end]="#003A77"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#005F6B"
theme[process_mid]="#003A77"
theme[process_end]="#781A61"

# Graph gradient colors (spectrum shades from background to foreground)
theme[gradient_color_0]="#FAF9F6"
theme[gradient_color_1]="#FFFFFF"
theme[gradient_color_2]="#8BA0BA"
theme[gradient_color_3]="#4B575E"
theme[gradient_color_4]="#4E4E49"
theme[gradient_color_5]="#2B2B28"
theme[gradient_color_6]="#1C1C1A"
theme[gradient_color_7]="#0F0F0E"
